paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  models_dir: "models"
  reports_dir: "reports"

heuristics:
  missing_value_drop_threshold: 0.90
  id_cardinality_threshold: 1.0
  high_cardinality_threshold: 0.10
  skewed_feature_threshold: 2.0

pipeline_params:
  numeric_imputer_strategy: "median"
  categorical_imputer_strategy: "most_frequent"
  high_cardinality_encoder: "target" # Options: 'target', 'hashing'
  hashing_n_features: 20
  imbalance_smote_threshold: 0.20

advanced_features:
  use_semantic_categorical_grouping: true

  semantic_grouping:
    embedding_model: "all-MiniLM-L6-v2"
    min_cluster_size: 2

drift_params:
  psi_threshold: 0.25
  ks_p_value_threshold: 0.05

feature_generation:
  enabled: true
  dfs_max_depth: 2
  memory_limit_mb: 2000
  max_features: 1000

feature_selection:
  enabled: false
  variance_threshold: 0.01
  correlation_threshold: 0.95
  max_features_model_based: 50

knowledge_graph:
  enabled: true
  backend: "neo4j"  # Options: "neo4j", "postgres"
  
  neo4j:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "password"
    database: "datainsight"
  
  postgres:
    connection_string: "postgresql://user:password@localhost:5432/datainsight"
    database: "datainsight"