"""Initial schema with auth and sessions

Revision ID: 487b50315dfa
Revises: 
Create Date: 2025-12-26 12:30:38.850769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "487b50315dfa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cancelled_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cancelled_tasks", schema=None) as batch_op:
        batch_op.create_index("idx_cancelled_session", ["session_id"], unique=False)
        batch_op.create_index("idx_cancelled_timestamp", ["cancelled_at"], unique=False)

    op.create_table(
        "dataset_characteristics",
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("n_samples", sa.Integer(), nullable=False),
        sa.Column("n_features", sa.Integer(), nullable=False),
        sa.Column("n_categorical", sa.Integer(), nullable=True),
        sa.Column("n_numerical", sa.Integer(), nullable=True),
        sa.Column("n_text", sa.Integer(), nullable=True),
        sa.Column("n_datetime", sa.Integer(), nullable=True),
        sa.Column("missing_ratio", sa.Float(), nullable=True),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_cardinality", sa.Integer(), nullable=True),
        sa.Column("class_imbalance_ratio", sa.Float(), nullable=True),
        sa.Column("correlation_strength", sa.Float(), nullable=True),
        sa.Column("skewness_avg", sa.Float(), nullable=True),
        sa.Column("kurtosis_avg", sa.Float(), nullable=True),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("task_complexity_score", sa.Float(), nullable=True),
        sa.Column("feature_diversity_score", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("dataset_hash"),
    )
    with op.batch_alter_table("dataset_characteristics", schema=None) as batch_op:
        batch_op.create_index("idx_dataset_complexity", ["task_complexity_score"], unique=False)
        batch_op.create_index("idx_dataset_domain", ["domain"], unique=False)
        batch_op.create_index("idx_dataset_quality", ["data_quality_score"], unique=False)
        batch_op.create_index("idx_dataset_type", ["target_type"], unique=False)

    op.create_table(
        "learning_patterns",
        sa.Column("pattern_id", sa.String(length=100), nullable=False),
        sa.Column("pattern_type", sa.String(length=50), nullable=False),
        sa.Column("dataset_context", sa.Text(), nullable=True),
        sa.Column("config_elements", sa.Text(), nullable=True),
        sa.Column("success_indicators", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("last_validated", sa.DateTime(), nullable=True),
        sa.Column("improvement_evidence", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pattern_id"),
    )
    with op.batch_alter_table("learning_patterns", schema=None) as batch_op:
        batch_op.create_index("idx_pattern_confidence", ["confidence_score"], unique=False)
        batch_op.create_index("idx_pattern_type", ["pattern_type"], unique=False)
        batch_op.create_index("idx_pattern_usage", ["usage_count"], unique=False)

    op.create_table(
        "model_registry",
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("hyperparameters", sa.Text(), nullable=True),
        sa.Column("blob_path", sa.String(length=500), nullable=False),
        sa.Column("blob_url", sa.String(length=1000), nullable=False),
        sa.Column("file_checksum", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("training_metrics", sa.Text(), nullable=True),
        sa.Column("model_version", sa.Integer(), nullable=True),
        sa.Column("framework", sa.String(length=50), nullable=True),
        sa.Column("dependencies", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("accessed_at", sa.DateTime(), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
    )
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.create_index("idx_model_active", ["is_active"], unique=False)
        batch_op.create_index("idx_model_dataset", ["dataset_hash"], unique=False)
        batch_op.create_index("idx_model_lookup", ["session_id", "dataset_hash", "model_type"], unique=False)
        batch_op.create_index("idx_model_session", ["session_id"], unique=False)
        batch_op.create_index("idx_model_type", ["model_type"], unique=False)
        batch_op.create_index("idx_model_user", ["user_id"], unique=False)

    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=True),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("performance_metrics", schema=None) as batch_op:
        batch_op.create_index("idx_perf_metric", ["metric_name"], unique=False)
        batch_op.create_index("idx_perf_session", ["session_id"], unique=False)
        batch_op.create_index("idx_perf_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "project_configs",
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("objective", sa.String(length=50), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("constraints", sa.Text(), nullable=True),
        sa.Column("strategy_applied", sa.String(length=100), nullable=False),
        sa.Column("feature_engineering_enabled", sa.Boolean(), nullable=True),
        sa.Column("feature_selection_enabled", sa.Boolean(), nullable=True),
        sa.Column("security_level", sa.String(length=20), nullable=True),
        sa.Column("privacy_level", sa.String(length=20), nullable=True),
        sa.Column("compliance_requirements", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("config_hash"),
    )
    with op.batch_alter_table("project_configs", schema=None) as batch_op:
        batch_op.create_index("idx_config_domain", ["domain"], unique=False)
        batch_op.create_index("idx_config_objective", ["objective"], unique=False)
        batch_op.create_index("idx_config_strategy", ["strategy_applied"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("dataset_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("report_data", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index("idx_reports_created", ["created_at"], unique=False)
        batch_op.create_index("idx_reports_session", ["session_id"], unique=False)
        batch_op.create_index("idx_reports_status", ["status"], unique=False)

    op.create_table(
        "system_metrics",
        sa.Column("metric_id", sa.String(length=100), nullable=False),
        sa.Column("metric_type", sa.String(length=50), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("metric_metadata", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("metric_id"),
    )
    with op.batch_alter_table("system_metrics", schema=None) as batch_op:
        batch_op.create_index("idx_metrics_timestamp", ["timestamp"], unique=False)
        batch_op.create_index("idx_metrics_type", ["metric_type"], unique=False)
        batch_op.create_index("idx_metrics_type_time", ["metric_type", "timestamp"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("google_oauth_id", sa.String(length=255), nullable=True),
        sa.Column("allow_email_notifications", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_oauth_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_user_active", ["is_active"], unique=False)
        batch_op.create_index("idx_user_email", ["email"], unique=False)
        batch_op.create_index("idx_user_google", ["google_oauth_id"], unique=False)

    op.create_table(
        "pipeline_executions",
        sa.Column("execution_id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("pipeline_stages", sa.Text(), nullable=True),
        sa.Column("execution_time", sa.Float(), nullable=True),
        sa.Column("final_performance", sa.Text(), nullable=True),
        sa.Column("trust_score", sa.Float(), nullable=True),
        sa.Column("validation_success", sa.Boolean(), nullable=True),
        sa.Column("budget_compliance_rate", sa.Float(), nullable=True),
        sa.Column("trade_off_efficiency", sa.Float(), nullable=True),
        sa.Column("user_satisfaction", sa.Float(), nullable=True),
        sa.Column("success_rating", sa.Float(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("recovery_attempts", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("execution_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["config_hash"],
            ["project_configs.config_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_hash"],
            ["dataset_characteristics.dataset_hash"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    with op.batch_alter_table("pipeline_executions", schema=None) as batch_op:
        batch_op.create_index("idx_execution_performance", ["success_rating", "trust_score"], unique=False)
        batch_op.create_index("idx_execution_session", ["session_id"], unique=False)
        batch_op.create_index("idx_execution_success", ["success_rating"], unique=False)
        batch_op.create_index("idx_execution_timestamp", ["timestamp"], unique=False)
        batch_op.create_index("idx_execution_validation", ["validation_success"], unique=False)

    op.create_table(
        "report_artifacts",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("report_id", sa.String(length=100), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("artifact_metadata", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_artifacts", schema=None) as batch_op:
        batch_op.create_index("idx_artifacts_report", ["report_id"], unique=False)
        batch_op.create_index("idx_artifacts_type", ["artifact_type"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("dataset_path", sa.String(length=500), nullable=True),
        sa.Column("dataset_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index("idx_session_accessed", ["last_accessed"], unique=False)
        batch_op.create_index("idx_session_user", ["user_id"], unique=False)

    op.create_table(
        "execution_feedback",
        sa.Column("feedback_id", sa.String(length=100), nullable=False),
        sa.Column("execution_id", sa.String(length=100), nullable=False),
        sa.Column("user_rating", sa.Float(), nullable=True),
        sa.Column("issues_encountered", sa.Text(), nullable=True),
        sa.Column("suggestions", sa.Text(), nullable=True),
        sa.Column("performance_expectation_met", sa.Boolean(), nullable=True),
        sa.Column("would_recommend", sa.Boolean(), nullable=True),
        sa.Column("feedback_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["pipeline_executions.execution_id"],
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    with op.batch_alter_table("execution_feedback", schema=None) as batch_op:
        batch_op.create_index("idx_feedback_execution", ["execution_id"], unique=False)
        batch_op.create_index("idx_feedback_rating", ["user_rating"], unique=False)
        batch_op.create_index("idx_feedback_timestamp", ["feedback_timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execution_feedback", schema=None) as batch_op:
        batch_op.drop_index("idx_feedback_timestamp")
        batch_op.drop_index("idx_feedback_rating")
        batch_op.drop_index("idx_feedback_execution")

    op.drop_table("execution_feedback")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_session_user")
        batch_op.drop_index("idx_session_accessed")

    op.drop_table("user_sessions")
    with op.batch_alter_table("report_artifacts", schema=None) as batch_op:
        batch_op.drop_index("idx_artifacts_type")
        batch_op.drop_index("idx_artifacts_report")

    op.drop_table("report_artifacts")
    with op.batch_alter_table("pipeline_executions", schema=None) as batch_op:
        batch_op.drop_index("idx_execution_validation")
        batch_op.drop_index("idx_execution_timestamp")
        batch_op.drop_index("idx_execution_success")
        batch_op.drop_index("idx_execution_session")
        batch_op.drop_index("idx_execution_performance")

    op.drop_table("pipeline_executions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_user_google")
        batch_op.drop_index("idx_user_email")
        batch_op.drop_index("idx_user_active")

    op.drop_table("users")
    with op.batch_alter_table("system_metrics", schema=None) as batch_op:
        batch_op.drop_index("idx_metrics_type_time")
        batch_op.drop_index("idx_metrics_type")
        batch_op.drop_index("idx_metrics_timestamp")

    op.drop_table("system_metrics")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("idx_reports_status")
        batch_op.drop_index("idx_reports_session")
        batch_op.drop_index("idx_reports_created")

    op.drop_table("reports")
    with op.batch_alter_table("project_configs", schema=None) as batch_op:
        batch_op.drop_index("idx_config_strategy")
        batch_op.drop_index("idx_config_objective")
        batch_op.drop_index("idx_config_domain")

    op.drop_table("project_configs")
    with op.batch_alter_table("performance_metrics", schema=None) as batch_op:
        batch_op.drop_index("idx_perf_timestamp")
        batch_op.drop_index("idx_perf_session")
        batch_op.drop_index("idx_perf_metric")

    op.drop_table("performance_metrics")
    with op.batch_alter_table("model_registry", schema=None) as batch_op:
        batch_op.drop_index("idx_model_user")
        batch_op.drop_index("idx_model_type")
        batch_op.drop_index("idx_model_session")
        batch_op.drop_index("idx_model_lookup")
        batch_op.drop_index("idx_model_dataset")
        batch_op.drop_index("idx_model_active")

    op.drop_table("model_registry")
    with op.batch_alter_table("learning_patterns", schema=None) as batch_op:
        batch_op.drop_index("idx_pattern_usage")
        batch_op.drop_index("idx_pattern_type")
        batch_op.drop_index("idx_pattern_confidence")

    op.drop_table("learning_patterns")
    with op.batch_alter_table("dataset_characteristics", schema=None) as batch_op:
        batch_op.drop_index("idx_dataset_type")
        batch_op.drop_index("idx_dataset_quality")
        batch_op.drop_index("idx_dataset_domain")
        batch_op.drop_index("idx_dataset_complexity")

    op.drop_table("dataset_characteristics")
    with op.batch_alter_table("cancelled_tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_cancelled_timestamp")
        batch_op.drop_index("idx_cancelled_session")

    op.drop_table("cancelled_tasks")
    # ### end Alembic commands ###
